@startuml

interface IProcessedDataRepository {
  + save(data: ProcessedData) : String
}
class DataRepositoryImpl implements IProcessedDataRepository {
  - dbConnection
  + save(data: ProcessedData) : String
}

interface IAuditNotifier {
  + notify(eventType: String, details: Map)
}
class AuditClient implements IAuditNotifier {
  - httpClient
  + notify(eventType: String, details: Map)
}

interface IHandler {
  + setNext(step: IHandler)
  + handle(dataContext: DataContext)
}
abstract class BaseHandler implements IHandler {
  - next: IHandler
  + setNext(step)
  + handle(dataContext: DataContext)
}
class TextHandler extends BaseHandler {
  + handle(dataContext: DataContext)
}
class ImageHandler extends BaseHandler {
  + handle(dataContext: DataContext)
}
class NumericHandler extends BaseHandler {
  + handle(dataContext: DataContext)
}
class SignalHandler extends BaseHandler {
  + handle(dataContext: DataContext)
}

class DataProcessingService {
  - repository: IProcessedDataRepository
  - auditNotifier: IAuditNotifier
  - chainHead: IHandler
 
  + processData(data: AnalyseRequest) : String
  + getProcessedData(dataId: String) : ProcessedData
}

DataProcessingService o-- "1" IProcessedDataRepository
DataProcessingService o-- "1" IAuditNotifier
DataProcessingService o-- "1" IHandler : (chainHead)

TextHandler o--> "1" ImageHandler : next
ImageHandler o--> "1" NumericHandler : next
NumericHandler o--> "1" SignalHandler : next

@enduml