@startuml

interface IAuthenticationClient {
  + register(data: RegisterRequest)
  + login(data: LoginRequest) : TokenResponse
  + validateToken(token: String) : String
}
interface IDataProcessingClient {
  + processData(data: AnalyseRequest) : String
}
interface IExplainableAIClient {
  + performAnalysis(dataId: String, strategy: String) : DiagnosisReport
  + getReports(doctorId: String, patientId: String) : List<ReportSummary>
}

class GatewayFacade {
  - authClient: IAuthenticationClient
  - dpClient: IDataProcessingClient
  - xaiClient: IExplainableAIClient

  + handleRegister(data: RegisterRequest)
  + handleLogin(data: LoginRequest)
  + handleAnalysis(data: AnalyseRequest, token: String, strategy: String)
  + handleGetReports(token: String, patientId: String)
}

GatewayFacade o-- "1" IAuthenticationClient
GatewayFacade o-- "1" IDataProcessingClient
GatewayFacade o-- "1" IExplainableAIClient

@enduml