@startuml

component "UI" as UI
component "Gateway" as Gateway
component "Authentication" as AuthService
component "Data Processing" as DataService
component "Explainable AI" as AIService
component "Audit" as AuditService
database "Doctors DB" as SQL_Doctors
database "Reports DB" as SQL_Reports
database "Processed Data DB" as NoSQLDB
database "Audit DB" as AuditDB

UI --> Gateway : User API calls
Gateway --> AuthService : POST authentication requests
Gateway --> DataService : POST raw data
Gateway --> AIService : POST processed data ID
AuthService --> SQL_Doctors : R/W doctor data
DataService --> NoSQLDB : R/W processed data
AIService --> SQL_Reports : R/W reports
AIService --> DataService : GET processed data
AuthService ..> AuditService : POST auth events
DataService ..> AuditService : POST processing events
AIService ..> AuditService : POST AI events
AuditService --> AuditDB : W events log

@enduml