@startuml

actor Doctor
participant "UI" as UI
participant "Gateway" as Gateway
participant "Authentication" as AuthService
participant "Explainable AI" as AIService
participant "Audit" as AuditService
database "Doctors DB" as DoctorsDB
database "Reports DB" as ReportsDB
database "Audit DB" as AuditDB

Doctor -> UI : View reports [option: by patient]
UI -> Gateway : Send JWT, [patient ID]
Gateway -> AuthService : Validate JWT
AuthService -> DoctorsDB : Query by doctor ID, [patient ID]

alt JWT valid
    Gateway -> AIService : Get reports
    AIService -> ReportsDB : Read reports
    AIService -> AuditService : Log reports event
    AuditService -> AuditDB : Write event log
    AIService --> Gateway : Return reports
    Gateway --> UI : Send reports
else JWT invalid
    AuthService -> Gateway : Return error
    Gateway --> UI : Send error message
end

UI --> Doctor : Show reports/error

@enduml